### ISSUE TITLE
Highschool

### ISSUE THREAD

**Issue by Rene123** [Wayzware/EducationBalancer#2]
The Highschool values are not stored in the config file.

**Comment by Wayzware** [comment]
It is possible to modify the high school values by adding this to your config:

```json
{
  "options" : [
    {
      "name": "HighSchool01",
      "upkeepCost": 10000,
      "studentCapacity": 1000
    },
    ...
  ]
}
```

In the next update, I'll add the high school and all other educational buildings in the config by default (though not with any more changes from vanilla) to make this easier.

**Comment by Wayzware** [comment]
Added in v0.1.2.
